//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EspionSpotify.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EspionSpotify.Translations.fr", typeof(fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Défaut.
        /// </summary>
        internal static string cbDefault {
            get {
                return ResourceManager.GetString("cbDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 128kbps.
        /// </summary>
        internal static string cbOptBitRate128 {
            get {
                return ResourceManager.GetString("cbOptBitRate128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 160kbps.
        /// </summary>
        internal static string cbOptBitRate160 {
            get {
                return ResourceManager.GetString("cbOptBitRate160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 256kbps.
        /// </summary>
        internal static string cbOptBitRate256 {
            get {
                return ResourceManager.GetString("cbOptBitRate256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 320kbps.
        /// </summary>
        internal static string cbOptBitRate320 {
            get {
                return ResourceManager.GetString("cbOptBitRate320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Spotify Free).
        /// </summary>
        internal static string cbOptBitRateSpotifyFree {
            get {
                return ResourceManager.GetString("cbOptBitRateSpotifyFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Haute qualité (Spotify Premium).
        /// </summary>
        internal static string cbOptBitRateSpotifyPremium {
            get {
                return ResourceManager.GetString("cbOptBitRateSpotifyPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisez Audacity (un éditeur gratuit pour fichiers audio) pour couper les parties audio que vous voulez retirer. Spytify ne peut garantir qu&apos;une annonce ou la prochaine piste audio sera détectée correctement puisqu&apos;il se base sur peu d&apos;informations disponible dans le processus de Spotify qui ne sont pas toujours précises..
        /// </summary>
        internal static string lblAdAndTrackOverlapOnRecordedTrack {
            get {
                return ResourceManager.GetString("lblAdAndTrackOverlapOnRecordedTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regrouper les chansons d&apos;un même artiste dans un dossier au nom de l&apos;artiste.
        /// </summary>
        internal static string lblAddFolders {
            get {
                return ResourceManager.GetString("lblAddFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remplacer les espaces par des underscores &quot;_&quot; dans le nom des fichiers sauvegardés.
        /// </summary>
        internal static string lblAddSeparators {
            get {
                return ResourceManager.GetString("lblAddSeparators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicités:.
        /// </summary>
        internal static string lblAds {
            get {
                return ResourceManager.GetString("lblAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fonctionnalité de Spytify &quot;Désactiver les publicités&quot; peut affecté la façon dont une annonce inconnue joue quand elle ne peut être bloquée. Essayez de ré-activer ce paramètre une fois de plus pour obtenir les derniers domaines de publicités bloqués ou désactivez ce paramètre et redémarrez les deux applications..
        /// </summary>
        internal static string lblAdsPlayAndStop {
            get {
                return ResourceManager.GetString("lblAdsPlayAndStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Périphérique audio:.
        /// </summary>
        internal static string lblAudioDevice {
            get {
                return ResourceManager.GetString("lblAudioDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premier cas, Spytify désactive la plupart des applications quand la session d&apos;enregistrement débute. Veuillez couper le son par le &quot;Mélangeur de volume&quot; des applications exécutées dans un processus d&apos;arrière-plan dans la barre d&apos;état système pouvant émettre un son ainsi que tout autre application que vous utilisez durant la session d&apos;enregistrement. Seulement Spotify et Spytify ne doivent pas être à muet..
        /// </summary>
        internal static string lblBackgroundNoiceRecordedOnTrack_first {
            get {
                return ResourceManager.GetString("lblBackgroundNoiceRecordedOnTrack_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deuxième cas, il se peut qu&apos;à l&apos;écoute des fichiers audio vous entendiez des sons (pops et craquements) jouant à des moments précis. Ces sons peuvent être liéés au fait que votre ordinateur n&apos;a pas le processeur de configuré à haute performance. Vous pouvez l&apos;activer dans vos paramètres de plan d&apos;alimentation ou en changeant la puissance minimale du processeur a 100 (voir sur internet pour un coment-faire). Ces sons peut être également liéés au fait que vous avez paramétré une qualité (bitrate) différente d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lblBackgroundNoiceRecordedOnTrack_second {
            get {
                return ResourceManager.GetString("lblBackgroundNoiceRecordedOnTrack_second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualité audio:.
        /// </summary>
        internal static string lblBitRate {
            get {
                return ResourceManager.GetString("lblBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désactiver le plus de publicités audio de Spotify.
        /// </summary>
        internal static string lblDisableAds {
            get {
                return ResourceManager.GetString("lblDisableAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dupliquer les pistes audio déjà enregistrées au lieu de passer au prochain..
        /// </summary>
        internal static string lblDuplicateAlreadyRecordedTrack {
            get {
                return ResourceManager.GetString("lblDuplicateAlreadyRecordedTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retarder le prochain enregistrement si du son est détecté.
        /// </summary>
        internal static string lblEndingSongDelay {
            get {
                return ResourceManager.GetString("lblEndingSongDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format audio:.
        /// </summary>
        internal static string lblFormat {
            get {
                return ResourceManager.GetString("lblFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langage:.
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durée minimale:.
        /// </summary>
        internal static string lblMinLength {
            get {
                return ResourceManager.GetString("lblMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couper le son des publicités.
        /// </summary>
        internal static string lblMuteAds {
            get {
                return ResourceManager.GetString("lblMuteAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrire au début du nom des fichiers enregistrés l&apos;ordre d&apos;enregistrement.
        /// </summary>
        internal static string lblNumFiles {
            get {
                return ResourceManager.GetString("lblNumFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remplacer le numéro de position cd (album track) par l&apos;ordre d&apos;enregistrement.
        /// </summary>
        internal static string lblNumTracks {
            get {
                return ResourceManager.GetString("lblNumTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossier de sauvegarde:.
        /// </summary>
        internal static string lblPath {
            get {
                return ResourceManager.GetString("lblPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistreur:.
        /// </summary>
        internal static string lblRecorder {
            get {
                return ResourceManager.GetString("lblRecorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier la position de départ du compteur de l&apos;ordre d&apos;enregistrement.
        /// </summary>
        internal static string lblRecordingNum {
            get {
                return ResourceManager.GetString("lblRecordingNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuteur pour la session d&apos;enregistrement.
        /// </summary>
        internal static string lblRecordingTimer {
            get {
                return ResourceManager.GetString("lblRecordingTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer les pistes de type inconnu détectées en tant que publicité.
        /// </summary>
        internal static string lblRecordUnknownTrackType {
            get {
                return ResourceManager.GetString("lblRecordUnknownTrackType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En utilisant le paramètre de Spotify &apos;&apos;Périphérique audio&apos;&apos;, vous pouvez déplacer Spytify vers un différent périphérique audio et utiliser le paramètre de Windows 10 pour déplacer Spotify vers le même périphérique audio. Cliquez sur Windows et tapez &apos;&apos;Paramètres de mélangeur audio&apos;&apos;, vous devriez arriver sur la page de paramètres appelée &apos;&apos;Volume d&apos;application et préférences de volume&apos;&apos;, soyez certain que Spotify est en train de jouer et paramétrez l&apos;application vers le bon périphérique avec la liste déroul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lblSpotifyAudioEndpoint {
            get {
                return ResourceManager.GetString("lblSpotifyAudioEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quand vous activez &quot;Désactiver les publicités&quot; dans les paramètres Spotify, vous acceptez que ces fonctionnalités ne pourront être disponible, c&apos;est pour s&apos;assurer que le plus d&apos;annonces possible soient désactivées. Parcontre, vous pouvez vous rendre ici &quot;C:\Windows\System32\drivers\etc\host&quot; pour modifier le fichier avec bloc-notes, recherchez le domaine &quot;spclient.wg.spotify.com&quot; et ajoutez un &quot;#&quot; au début de la ligne pour le rendre inactif..
        /// </summary>
        internal static string lblSpotifyLostFeatures {
            get {
                return ResourceManager.GetString("lblSpotifyLostFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify recherche les fichiers de musique localement avant de jouer une piste audio, si il en trouve une avec les méta données que la piste audio courante, il jouera la piste audio local à la place. Des pistes audio coupées signifient que vous avez, une fois, commencer une session d&apos;enregistrement et l&apos;avez terminé trop tôt. Il faut juste supprimer les pistes audio incomplètes dans votre répertoire de musique pour résoudre le problème..
        /// </summary>
        internal static string lblSpotifyTrackCut {
            get {
                return ResourceManager.GetString("lblSpotifyTrackCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espion:.
        /// </summary>
        internal static string lblSpy {
            get {
                return ResourceManager.GetString("lblSpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcast, livre audio et tout autre piste de type non commun sont détectés en tant que publicité. Également, Spotify ne retourne pas les bonnes informations à Spytify lorsque vous basculez entre radios, listes de lecture ou albums, résultant en une piste audio détectée en tant que publicté. Si ceci se produit, rejouer la piste courante, si ceci se produit trop souvent, sauvegarder vos pistes dans une playlist et jouer la. Spytify ne peut garantir qu&apos;une piste audio sera détectée correctement puisqu&apos;il se bas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lblTrackDetectedAsAd {
            get {
                return ResourceManager.GetString("lblTrackDetectedAsAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annonce.
        /// </summary>
        internal static string logAd {
            get {
                return ResourceManager.GetString("logAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Une publicité est en train de jouer..
        /// </summary>
        internal static string logAdPlaying {
            get {
                return ResourceManager.GetString("logAdPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacement de: {0} [&lt; {1}s].
        /// </summary>
        internal static string logDeleting {
            get {
                return ResourceManager.GetString("logDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Erreur lors de l&apos;enregistrement: Le répertoire de sauvegarde est introuvable..
        /// </summary>
        internal static string logInvalidOutput {
            get {
                return ResourceManager.GetString("logInvalidOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Erreur lors de l&apos;enregistrement: L&apos;accès au répertoire de sauvegarde est refusé, éxécutez Spytify en tant qu&apos;administrateur ou changez le pour un autre..
        /// </summary>
        internal static string logNoAccessOutput {
            get {
                return ResourceManager.GetString("logNoAccessOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconnu.
        /// </summary>
        internal static string logOther {
            get {
                return ResourceManager.GetString("logOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Le registre de la session d&apos;enregistrement précédente.
        /// </summary>
        internal static string logPreviousLogs {
            get {
                return ResourceManager.GetString("logPreviousLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistré {0} en : {1}.
        /// </summary>
        internal static string logRecorded {
            get {
                return ResourceManager.GetString("logRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrement de: {0}.
        /// </summary>
        internal static string logRecording {
            get {
                return ResourceManager.GetString("logRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Minuteur de session d&apos;enregistrement terminé..
        /// </summary>
        internal static string logRecordingTimerDone {
            get {
                return ResourceManager.GetString("logRecordingTimerDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Spotify n&apos;est pas démarré, tentative de lancement amorcée..
        /// </summary>
        internal static string logSpotifyConnecting {
            get {
                return ResourceManager.GetString("logSpotifyConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Spotify est fermé..
        /// </summary>
        internal static string logSpotifyIsClosed {
            get {
                return ResourceManager.GetString("logSpotifyIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Spotify ne s&apos;est pas connecté à l&apos;API local, veuillez ré-essayer..
        /// </summary>
        internal static string logSpotifyNotConnected {
            get {
                return ResourceManager.GetString("logSpotifyNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Spotify n&apos;a pas été trouvé ou n&apos;est pas installé..
        /// </summary>
        internal static string logSpotifyNotFound {
            get {
                return ResourceManager.GetString("logSpotifyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Spytify ne peut enregistré s&apos;il n&apos;utilise pas le même périphérique audio que Spotify. Voir la F.A.Q pour savoir comment déplacer Spotify vers un autre périphérique..
        /// </summary>
        internal static string logSpotifyPlayingOutsideOfSelectedAudioEndPoint {
            get {
                return ResourceManager.GetString("logSpotifyPlayingOutsideOfSelectedAudioEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Début de l&apos;espionnage..
        /// </summary>
        internal static string logStarting {
            get {
                return ResourceManager.GetString("logStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Fin de l&apos;espionnage..
        /// </summary>
        internal static string logStoping {
            get {
                return ResourceManager.GetString("logStoping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // En attente de la fin de l&apos;enregistrement de la piste audio courante.
        /// </summary>
        internal static string logStopRecordingWhenSongEnds {
            get {
                return ResourceManager.GetString("logStopRecordingWhenSongEnds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Passe: {0} (l&apos;enregistrement existe déjà).
        /// </summary>
        internal static string logTrackExists {
            get {
                return ResourceManager.GetString("logTrackExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Erreur lors de l&apos;enregistrement: Exception inconnue: {0}.
        /// </summary>
        internal static string logUnknownException {
            get {
                return ResourceManager.GetString("logUnknownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Erreur lors de l&apos;enregistrement: L&apos;enregistrement multi-canaux de fichiers n&apos;est pas supporté ({0} canaux), veuillez réduire le nombre de canaux à 2 (stéréo) ou 1 (mono)..
        /// </summary>
        internal static string logUnsupportedNumberChannels {
            get {
                return ResourceManager.GetString("logUnsupportedNumberChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Erreur lors de l&apos;enregistrement: Format audio de votre ordinateur non supporté. Le format doit être &apos;2 canaux, 24 bit, 48000 Hz (Studio Quality)&apos; (Panneau de configuration &gt; Son &gt; Propriétés &gt; Avancés)..
        /// </summary>
        internal static string logUnsupportedRate {
            get {
                return ResourceManager.GetString("logUnsupportedRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // En attente du prochain titre....
        /// </summary>
        internal static string logWaiting {
            get {
                return ResourceManager.GetString("logWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous quand même quitter?.
        /// </summary>
        internal static string msgBodyCantQuit {
            get {
                return ResourceManager.GetString("msgBodyCantQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En désactivant les annonces, vous bloquerez les annonces provenant de partenaires (domaines tiers). Spotify pourra quand même jouer leurs propre annonces, puisqu&apos;elles viennent du même domaine que leur contenu musical, radio, liste d&apos;amis et &quot;daily mix&quot;..
        /// </summary>
        internal static string msgBodyDisableAds {
            get {
                return ResourceManager.GetString("msgBodyDisableAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le répertoire de sauvegarde sélectionné n&apos;existe pas, sélectionner un autre..
        /// </summary>
        internal static string msgBodyPathNotFound {
            get {
                return ResourceManager.GetString("msgBodyPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spytify doit redémarrer pour obtenir les droits d&apos;administrateur et pouvoir désactiver les publicités de Spotify. Voulez-vous poursuivre et réessayer?.
        /// </summary>
        internal static string msgEnsureAdminContent {
            get {
                return ResourceManager.GetString("msgEnsureAdminContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droits d&apos;administrateur requis.
        /// </summary>
        internal static string msgEnsureAdminTitle {
            get {
                return ResourceManager.GetString("msgEnsureAdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous ouvrir GitHub pour voir la dernière version de Spytify?.
        /// </summary>
        internal static string msgNewVersionContent {
            get {
                return ResourceManager.GetString("msgNewVersionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} a été publiée!.
        /// </summary>
        internal static string msgNewVersionTitle {
            get {
                return ResourceManager.GetString("msgNewVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espionnage Spotify en cours.
        /// </summary>
        internal static string msgTitleCantQuit {
            get {
                return ResourceManager.GetString("msgTitleCantQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désactiver les annonces.
        /// </summary>
        internal static string msgTitleDisableAds {
            get {
                return ResourceManager.GetString("msgTitleDisableAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Répertoire invalide.
        /// </summary>
        internal static string msgTitlePathNotFound {
            get {
                return ResourceManager.GetString("msgTitlePathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres avancés.
        /// </summary>
        internal static string tabAdvanced {
            get {
                return ResourceManager.GetString("tabAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.A.Q..
        /// </summary>
        internal static string tabFAQ {
            get {
                return ResourceManager.GetString("tabFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espion.
        /// </summary>
        internal static string tabRecord {
            get {
                return ResourceManager.GetString("tabRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        internal static string tabSettings {
            get {
                return ResourceManager.GetString("tabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer l&apos;historique.
        /// </summary>
        internal static string tipClear {
            get {
                return ResourceManager.GetString("tipClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir le répertoire de sauvegarde.
        /// </summary>
        internal static string tipDirectory {
            get {
                return ResourceManager.GetString("tipDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcourir.
        /// </summary>
        internal static string tipPath {
            get {
                return ResourceManager.GetString("tipPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle version disponible.
        /// </summary>
        internal static string tipRelease {
            get {
                return ResourceManager.GetString("tipRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Débuter l&apos;espionnage.
        /// </summary>
        internal static string tipStartSpying {
            get {
                return ResourceManager.GetString("tipStartSpying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrêter l&apos;espionnage.
        /// </summary>
        internal static string tipStopSying {
            get {
                return ResourceManager.GetString("tipStopSying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annonces et pistes audio chevauchent au début/fin d&apos;une piste audio enregistrée..
        /// </summary>
        internal static string tlAdAndTrackOverlapOnRecordedTrack {
            get {
                return ResourceManager.GetString("tlAdAndTrackOverlapOnRecordedTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify joue encore des annonces après les avoir désactivées et il se met sur pause/joue à chaque seconde..
        /// </summary>
        internal static string tlAdsPlayAndStop {
            get {
                return ResourceManager.GetString("tlAdsPlayAndStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du son/bruit d&apos;arrière fond a été enregistré dans le fichier de la piste audio..
        /// </summary>
        internal static string tlBackgroundNoiceRecordedOnTrack {
            get {
                return ResourceManager.GetString("tlBackgroundNoiceRecordedOnTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isoler l&apos;audio de Spotify vers un différent périphérique audio.
        /// </summary>
        internal static string tlSpotifyAudioEndpoint {
            get {
                return ResourceManager.GetString("tlSpotifyAudioEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify a perdu quelques fonctionnalités après avoir désactivé les publicités: Liste d&apos;amis, radio, mixes journaliers et podcasts..
        /// </summary>
        internal static string tlSpotifyLostFeatures {
            get {
                return ResourceManager.GetString("tlSpotifyLostFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify joue seulement un bout d&apos;une piste audio, ça coupe après quelques secondes..
        /// </summary>
        internal static string tlSpotifyTrackCut {
            get {
                return ResourceManager.GetString("tlSpotifyTrackCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pistes audio sont détectées en tant que publicité.
        /// </summary>
        internal static string tlTrackDetectedAsAd {
            get {
                return ResourceManager.GetString("tlTrackDetectedAsAd", resourceCulture);
            }
        }
    }
}
