//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EspionSpotify.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EspionSpotify.Translations.fr", typeof(fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 128kbps.
        /// </summary>
        internal static string cbOptBitRate128 {
            get {
                return ResourceManager.GetString("cbOptBitRate128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 160kbps.
        /// </summary>
        internal static string cbOptBitRate160 {
            get {
                return ResourceManager.GetString("cbOptBitRate160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 256kbps.
        /// </summary>
        internal static string cbOptBitRate256 {
            get {
                return ResourceManager.GetString("cbOptBitRate256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 320kbps.
        /// </summary>
        internal static string cbOptBitRate320 {
            get {
                return ResourceManager.GetString("cbOptBitRate320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Spotify Free).
        /// </summary>
        internal static string cbOptBitRateSpotifyFree {
            get {
                return ResourceManager.GetString("cbOptBitRateSpotifyFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Haute qualité (Spotify Premium).
        /// </summary>
        internal static string cbOptBitRateSpotifyPremium {
            get {
                return ResourceManager.GetString("cbOptBitRateSpotifyPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annonce.
        /// </summary>
        internal static string lblAd {
            get {
                return ResourceManager.GetString("lblAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer des répertoires en regroupant les pistes audio par artiste et album.
        /// </summary>
        internal static string lblAddFolders {
            get {
                return ResourceManager.GetString("lblAddFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remplacer les espaces par des underscores &quot;_&quot; dans le nom des fichiers sauvegardés.
        /// </summary>
        internal static string lblAddSeparators {
            get {
                return ResourceManager.GetString("lblAddSeparators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicités:.
        /// </summary>
        internal static string lblAds {
            get {
                return ResourceManager.GetString("lblAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrire au début du nom des fichiers enregistrés le numéro de position cd (album track).
        /// </summary>
        internal static string lblAlbumTrackNumberToFilePrefix {
            get {
                return ResourceManager.GetString("lblAlbumTrackNumberToFilePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Périphérique audio:.
        /// </summary>
        internal static string lblAudioDevice {
            get {
                return ResourceManager.GetString("lblAudioDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualité audio:.
        /// </summary>
        internal static string lblBitRate {
            get {
                return ResourceManager.GetString("lblBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID:.
        /// </summary>
        internal static string lblClientId {
            get {
                return ResourceManager.GetString("lblClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrire au début du nom des fichiers enregistrés la valeur du compteur.
        /// </summary>
        internal static string lblCounterToFilePrefix {
            get {
                return ResourceManager.GetString("lblCounterToFilePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remplacer le tag numéro de position cd (album track) par la valeur du compteur.
        /// </summary>
        internal static string lblCounterToMediaTag {
            get {
                return ResourceManager.GetString("lblCounterToMediaTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dupliquer.
        /// </summary>
        internal static string lblDuplicate {
            get {
                return ResourceManager.GetString("lblDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déplacer l&apos;extra du titre de la piste audio dans le tag second titre.
        /// </summary>
        internal static string lblExtraTitleToSubtitle {
            get {
                return ResourceManager.GetString("lblExtraTitleToSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Spotify à sauter les pistes déjà enregistrées.
        /// </summary>
        internal static string lblForceSpotifyToSkip {
            get {
                return ResourceManager.GetString("lblForceSpotifyToSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format audio:.
        /// </summary>
        internal static string lblFormat {
            get {
                return ResourceManager.GetString("lblFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Général:.
        /// </summary>
        internal static string lblGeneral {
            get {
                return ResourceManager.GetString("lblGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags ID3:.
        /// </summary>
        internal static string lblID3 {
            get {
                return ResourceManager.GetString("lblID3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langage:.
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toujours écouter la lecture courante de Spotify sur le périphérique par défaut..
        /// </summary>
        internal static string lblListenToSpotifyPlayback {
            get {
                return ResourceManager.GetString("lblListenToSpotifyPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réduire dans la barre des tâches.
        /// </summary>
        internal static string lblMinimizeToSystemTray {
            get {
                return ResourceManager.GetString("lblMinimizeToSystemTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durée minimale:.
        /// </summary>
        internal static string lblMinLength {
            get {
                return ResourceManager.GetString("lblMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couper le son des publicités.
        /// </summary>
        internal static string lblMuteAds {
            get {
                return ResourceManager.GetString("lblMuteAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossier de sauvegarde:.
        /// </summary>
        internal static string lblPath {
            get {
                return ResourceManager.GetString("lblPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluant les annonces.
        /// </summary>
        internal static string lblRecordAds {
            get {
                return ResourceManager.GetString("lblRecordAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistreur:.
        /// </summary>
        internal static string lblRecorder {
            get {
                return ResourceManager.GetString("lblRecorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer tout (comme les podcasts)..
        /// </summary>
        internal static string lblRecordEverything {
            get {
                return ResourceManager.GetString("lblRecordEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier la position de départ du compteur.
        /// </summary>
        internal static string lblRecordingNum {
            get {
                return ResourceManager.GetString("lblRecordingNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuteur pour la session d&apos;enregistrement.
        /// </summary>
        internal static string lblRecordingTimer {
            get {
                return ResourceManager.GetString("lblRecordingTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer les pistes audio déjà enregistrées au lieu de passer au prochain..
        /// </summary>
        internal static string lblRecordOverRecordings {
            get {
                return ResourceManager.GetString("lblRecordOverRecordings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL de redirection:.
        /// </summary>
        internal static string lblRedirectURL {
            get {
                return ResourceManager.GetString("lblRedirectURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Secret:.
        /// </summary>
        internal static string lblSecretId {
            get {
                return ResourceManager.GetString("lblSecretId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espion:.
        /// </summary>
        internal static string lblSpy {
            get {
                return ResourceManager.GetString("lblSpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remettre à jour les tags ID3 des pistes audio déjà enregistrées lors de leur lecture.
        /// </summary>
        internal static string lblUpdateRecordingsID3Tags {
            get {
                return ResourceManager.GetString("lblUpdateRecordingsID3Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Annonce.
        /// </summary>
        internal static string logAd {
            get {
                return ResourceManager.GetString("logAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacement de: {0} [&lt; {1}s].
        /// </summary>
        internal static string logDeleting {
            get {
                return ResourceManager.GetString("logDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Erreur: {0}.
        /// </summary>
        internal static string logException {
            get {
                return ResourceManager.GetString("logException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Compteur: Max de la séquence de préfix de fichier de {0} atteint.
        /// </summary>
        internal static string logMaxFileSequenceReached {
            get {
                return ResourceManager.GetString("logMaxFileSequenceReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Erreur: Fichiers DLL manquants - libmp3lame.32.dll et libmp3lame.64.dll.
        /// </summary>
        internal static string logMissingDlls {
            get {
                return ResourceManager.GetString("logMissingDlls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Erreur: Le dossier de sauvegarde n&apos;existe plus.
        /// </summary>
        internal static string logOutputPathNotFound {
            get {
                return ResourceManager.GetString("logOutputPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Le registre de la session d&apos;enregistrement précédente.
        /// </summary>
        internal static string logPreviousLogs {
            get {
                return ResourceManager.GetString("logPreviousLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistré: {0} en {1}.
        /// </summary>
        internal static string logRecorded {
            get {
                return ResourceManager.GetString("logRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Erreur: Le fichier d&apos;enregistrement a été perdu durant la procédure.
        /// </summary>
        internal static string logRecordedFileNotFound {
            get {
                return ResourceManager.GetString("logRecordedFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrement de: {0}.
        /// </summary>
        internal static string logRecording {
            get {
                return ResourceManager.GetString("logRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Minuteur de session d&apos;enregistrement terminé..
        /// </summary>
        internal static string logRecordingTimerDone {
            get {
                return ResourceManager.GetString("logRecordingTimerDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Spotify n&apos;est pas démarré, tentative de lancement amorcée..
        /// </summary>
        internal static string logSpotifyConnecting {
            get {
                return ResourceManager.GetString("logSpotifyConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Spotify est fermé..
        /// </summary>
        internal static string logSpotifyIsClosed {
            get {
                return ResourceManager.GetString("logSpotifyIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Spotify ne s&apos;est pas connecté à l&apos;API local, veuillez ré-essayer..
        /// </summary>
        internal static string logSpotifyNotConnected {
            get {
                return ResourceManager.GetString("logSpotifyNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Spotify n&apos;a pas été trouvé ou n&apos;est pas installé..
        /// </summary>
        internal static string logSpotifyNotFound {
            get {
                return ResourceManager.GetString("logSpotifyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Spytify ne peut enregistrer s&apos;il n&apos;utilise pas le même périphérique audio que Spotify. Voir la F.A.Q en ligne pour savoir comment déplacer Spotify vers un autre périphérique..
        /// </summary>
        internal static string logSpotifyPlayingOutsideOfSelectedAudioEndPoint {
            get {
                return ResourceManager.GetString("logSpotifyPlayingOutsideOfSelectedAudioEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Début de l&apos;espionnage..
        /// </summary>
        internal static string logStarting {
            get {
                return ResourceManager.GetString("logStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Fin de l&apos;espionnage..
        /// </summary>
        internal static string logStoping {
            get {
                return ResourceManager.GetString("logStoping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // En attente de la fin de l&apos;enregistrement de la piste audio courante.
        /// </summary>
        internal static string logStopRecordingWhenSongEnds {
            get {
                return ResourceManager.GetString("logStopRecordingWhenSongEnds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passe: {0} (l&apos;enregistrement existe déjà).
        /// </summary>
        internal static string logTrackExists {
            get {
                return ResourceManager.GetString("logTrackExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Erreur: Exception inconnue: {0}.
        /// </summary>
        internal static string logUnknownException {
            get {
                return ResourceManager.GetString("logUnknownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Attention: L&apos;audio {0}-canaux n&apos;est pas supporté. L&apos;audio sera encodé en stéréo (2)..
        /// </summary>
        internal static string logUnsupportedNumberChannels {
            get {
                return ResourceManager.GetString("logUnsupportedNumberChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Attention: Le taux d&apos;échantillon audio de {0}Hz n&apos;est pas supporté. L&apos;audio sera encodé en 48000Hz..
        /// </summary>
        internal static string logUnsupportedRate {
            get {
                return ResourceManager.GetString("logUnsupportedRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous quand même quitter?.
        /// </summary>
        internal static string msgBodyCantQuit {
            get {
                return ResourceManager.GetString("msgBodyCantQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de l&apos;ouverture du controlleur Audio Virtual Cable..
        /// </summary>
        internal static string msgBodyDriverInstallationFailed {
            get {
                return ResourceManager.GetString("msgBodyDriverInstallationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion perdue avec Spotify API. Soyez certain d&apos;autoriser Spytify sur le même compte Spotify présentement connecté à Spotify-Desktop pour être capable de récupérer les métadonnées de la piste courante. Aussi, validez que l&apos;appareil actif en ce moment est bien votre PC et revalidez les Client_ID et Client_Secret saisis dans Spytify. Entre temps Spytify utilisera LastFM API..
        /// </summary>
        internal static string msgBodyFailedToUseSpotifyAPI {
            get {
                return ResourceManager.GetString("msgBodyFailedToUseSpotifyAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le répertoire de sauvegarde sélectionné n&apos;existe pas, sélectionner un autre..
        /// </summary>
        internal static string msgBodyPathNotFound {
            get {
                return ResourceManager.GetString("msgBodyPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez un autre répertoire, le dossier de sauvegarde sélectionné est trop long..
        /// </summary>
        internal static string msgBodyPathTooLong {
            get {
                return ResourceManager.GetString("msgBodyPathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez choisir le dossier où vous désirez sauvegarder les fichiers audio enregistrés..
        /// </summary>
        internal static string msgFolderDialog {
            get {
                return ResourceManager.GetString("msgFolderDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous mettre à jour à la dernière version de Spytify?.
        /// </summary>
        internal static string msgNewVersionContent {
            get {
                return ResourceManager.GetString("msgNewVersionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} a été publiée!.
        /// </summary>
        internal static string msgNewVersionTitle {
            get {
                return ResourceManager.GetString("msgNewVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espionnage Spotify en cours.
        /// </summary>
        internal static string msgTitleCantQuit {
            get {
                return ResourceManager.GetString("msgTitleCantQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify API a échoué.
        /// </summary>
        internal static string msgTitleFailedToUseSpotifyAPI {
            get {
                return ResourceManager.GetString("msgTitleFailedToUseSpotifyAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Répertoire invalide.
        /// </summary>
        internal static string msgTitlePathNotFound {
            get {
                return ResourceManager.GetString("msgTitlePathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossier de sauvegarde trop long.
        /// </summary>
        internal static string msgTitlePathTooLong {
            get {
                return ResourceManager.GetString("msgTitlePathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres avancés.
        /// </summary>
        internal static string tabAdvanced {
            get {
                return ResourceManager.GetString("tabAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espion.
        /// </summary>
        internal static string tabRecord {
            get {
                return ResourceManager.GetString("tabRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        internal static string tabSettings {
            get {
                return ResourceManager.GetString("tabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer l&apos;historique.
        /// </summary>
        internal static string tipClear {
            get {
                return ResourceManager.GetString("tipClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir le répertoire de sauvegarde.
        /// </summary>
        internal static string tipDirectory {
            get {
                return ResourceManager.GetString("tipDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faire un don à Spytify.
        /// </summary>
        internal static string tipDonate {
            get {
                return ResourceManager.GetString("tipDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir la F.A.Q..
        /// </summary>
        internal static string tipFAQ {
            get {
                return ResourceManager.GetString("tipFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voyez comment configurer et utiliser Spotify API.
        /// </summary>
        internal static string tipFAQSpotifyAPI {
            get {
                return ResourceManager.GetString("tipFAQSpotifyAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer Audio Virtual Cable.
        /// </summary>
        internal static string tipInstallVirtualCableDriver {
            get {
                return ResourceManager.GetString("tipInstallVirtualCableDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTRL affecte la valeur du masque.
        /// </summary>
        internal static string tipNumModifierHold {
            get {
                return ResourceManager.GetString("tipNumModifierHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcourir.
        /// </summary>
        internal static string tipPath {
            get {
                return ResourceManager.GetString("tipPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle version disponible.
        /// </summary>
        internal static string tipRelease {
            get {
                return ResourceManager.GetString("tipRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer les identifiants Spotify API.
        /// </summary>
        internal static string tipSpotifyAPICredentials {
            get {
                return ResourceManager.GetString("tipSpotifyAPICredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tableau de bord de Spotify API.
        /// </summary>
        internal static string tipSpotifyAPIDashboard {
            get {
                return ResourceManager.GetString("tipSpotifyAPIDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Débuter l&apos;espionnage.
        /// </summary>
        internal static string tipStartSpying {
            get {
                return ResourceManager.GetString("tipStartSpying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrêter l&apos;espionnage.
        /// </summary>
        internal static string tipStopSying {
            get {
                return ResourceManager.GetString("tipStopSying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désinstaller Audio Virtual Cable.
        /// </summary>
        internal static string tipUninstallVirtualCableDriver {
            get {
                return ResourceManager.GetString("tipUninstallVirtualCableDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiants Spotify API.
        /// </summary>
        internal static string titleSpotifyAPICredentials {
            get {
                return ResourceManager.GetString("titleSpotifyAPICredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coller le Client ID ici.
        /// </summary>
        internal static string watermarkClientId {
            get {
                return ResourceManager.GetString("watermarkClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collez votre URL de redirection ici.
        /// </summary>
        internal static string watermarkRedirectURL {
            get {
                return ResourceManager.GetString("watermarkRedirectURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coller le Client Secret ici.
        /// </summary>
        internal static string watermarkSecretId {
            get {
                return ResourceManager.GetString("watermarkSecretId", resourceCulture);
            }
        }
    }
}
