//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EspionSpotify.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EspionSpotify.Translations.pl", typeof(pl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 128kbps.
        /// </summary>
        internal static string cbOptBitRate128 {
            get {
                return ResourceManager.GetString("cbOptBitRate128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 160kbps.
        /// </summary>
        internal static string cbOptBitRate160 {
            get {
                return ResourceManager.GetString("cbOptBitRate160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 256kbps.
        /// </summary>
        internal static string cbOptBitRate256 {
            get {
                return ResourceManager.GetString("cbOptBitRate256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 320kbps.
        /// </summary>
        internal static string cbOptBitRate320 {
            get {
                return ResourceManager.GetString("cbOptBitRate320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Spotify Free).
        /// </summary>
        internal static string cbOptBitRateSpotifyFree {
            get {
                return ResourceManager.GetString("cbOptBitRateSpotifyFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Wysoka jakość (Spotify Premium).
        /// </summary>
        internal static string cbOptBitRateSpotifyPremium {
            get {
                return ResourceManager.GetString("cbOptBitRateSpotifyPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupuj utwory w folderach.
        /// </summary>
        internal static string lblAddFolders {
            get {
                return ResourceManager.GetString("lblAddFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamień w nazwach spacje na podkreśliniki &quot;_&quot;.
        /// </summary>
        internal static string lblAddSeparators {
            get {
                return ResourceManager.GetString("lblAddSeparators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reklamy:.
        /// </summary>
        internal static string lblAds {
            get {
                return ResourceManager.GetString("lblAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odtwarzacz audio:.
        /// </summary>
        internal static string lblAudioDevice {
            get {
                return ResourceManager.GetString("lblAudioDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jakość audio:.
        /// </summary>
        internal static string lblBitRate {
            get {
                return ResourceManager.GetString("lblBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID:.
        /// </summary>
        internal static string lblClientId {
            get {
                return ResourceManager.GetString("lblClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplikuj.
        /// </summary>
        internal static string lblDuplicate {
            get {
                return ResourceManager.GetString("lblDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opóźnij następne nagranie jeśli wykryto dźwięk.
        /// </summary>
        internal static string lblEndingSongDelay {
            get {
                return ResourceManager.GetString("lblEndingSongDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przenieś dodatkowy tytuł ścieżki do znacznika napisów.
        /// </summary>
        internal static string lblExtraTitleToSubtitle {
            get {
                return ResourceManager.GetString("lblExtraTitleToSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format audio:.
        /// </summary>
        internal static string lblFormat {
            get {
                return ResourceManager.GetString("lblFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogólne:.
        /// </summary>
        internal static string lblGeneral {
            get {
                return ResourceManager.GetString("lblGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3 Tags:.
        /// </summary>
        internal static string lblID3 {
            get {
                return ResourceManager.GetString("lblID3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Język:.
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zminimalizuj do zasobnika systemowego.
        /// </summary>
        internal static string lblMinimizeToSystemTray {
            get {
                return ResourceManager.GetString("lblMinimizeToSystemTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalna długość:.
        /// </summary>
        internal static string lblMinLength {
            get {
                return ResourceManager.GetString("lblMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wycisz reklamy.
        /// </summary>
        internal static string lblMuteAds {
            get {
                return ResourceManager.GetString("lblMuteAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj numer licznika przed nazwą wszystkich plików.
        /// </summary>
        internal static string lblNumFiles {
            get {
                return ResourceManager.GetString("lblNumFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zastąp tag numeru ścieżki wartością licznika.
        /// </summary>
        internal static string lblNumTracks {
            get {
                return ResourceManager.GetString("lblNumTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ścieżka docelowa:.
        /// </summary>
        internal static string lblPath {
            get {
                return ResourceManager.GetString("lblPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W tym reklamy.
        /// </summary>
        internal static string lblRecordAds {
            get {
                return ResourceManager.GetString("lblRecordAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nagrywanie:.
        /// </summary>
        internal static string lblRecorder {
            get {
                return ResourceManager.GetString("lblRecorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nagrywaj wszystko..
        /// </summary>
        internal static string lblRecordEverything {
            get {
                return ResourceManager.GetString("lblRecordEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz pozycję początkową licznika.
        /// </summary>
        internal static string lblRecordingNum {
            get {
                return ResourceManager.GetString("lblRecordingNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licznik czasu sesji nagraniowej.
        /// </summary>
        internal static string lblRecordingTimer {
            get {
                return ResourceManager.GetString("lblRecordingTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nagraj ponownie już istniejące utwory.
        /// </summary>
        internal static string lblRecordOverRecordings {
            get {
                return ResourceManager.GetString("lblRecordOverRecordings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres URL przekierowania:.
        /// </summary>
        internal static string lblRedirectURL {
            get {
                return ResourceManager.GetString("lblRedirectURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Secret:.
        /// </summary>
        internal static string lblSecretId {
            get {
                return ResourceManager.GetString("lblSecretId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szpieguj:.
        /// </summary>
        internal static string lblSpy {
            get {
                return ResourceManager.GetString("lblSpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponownie aktualizuj już zarejestrowane tagi ID3 ścieżek podczas ich odtwarzania.
        /// </summary>
        internal static string lblUpdateRecordingsID3Tags {
            get {
                return ResourceManager.GetString("lblUpdateRecordingsID3Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reklama.
        /// </summary>
        internal static string logAd {
            get {
                return ResourceManager.GetString("logAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuwam: {0} [&lt; {1}s].
        /// </summary>
        internal static string logDeleting {
            get {
                return ResourceManager.GetString("logDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Błąd: {0}.
        /// </summary>
        internal static string logException {
            get {
                return ResourceManager.GetString("logException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Licznik: osiągnięto maksymalny prefiks sekwencji plików z {0}.
        /// </summary>
        internal static string logMaxFileSequenceReached {
            get {
                return ResourceManager.GetString("logMaxFileSequenceReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Błąd: brak plików DLL - libmp3lame.32.dll i libmp3lame.64.dll.
        /// </summary>
        internal static string logMissingDlls {
            get {
                return ResourceManager.GetString("logMissingDlls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Dzienniki poprzedniej sesji.
        /// </summary>
        internal static string logPreviousLogs {
            get {
                return ResourceManager.GetString("logPreviousLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nagrane {0} in: {1}.
        /// </summary>
        internal static string logRecorded {
            get {
                return ResourceManager.GetString("logRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nagrywane: {0}.
        /// </summary>
        internal static string logRecording {
            get {
                return ResourceManager.GetString("logRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Nagranie {0} miało przekroczyć ilość danych, często z powodu braku odpowiedzi Spotify po zbyt długim przebywaniu w tle lub w trybie oszczędzania energii..
        /// </summary>
        internal static string logRecordingDataExceeded {
            get {
                return ResourceManager.GetString("logRecordingDataExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Czas nagrywania sesji zakończony..
        /// </summary>
        internal static string logRecordingTimerDone {
            get {
                return ResourceManager.GetString("logRecordingTimerDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Spotify nie jest włączone, spróbuj je uruchomić.
        /// </summary>
        internal static string logSpotifyConnecting {
            get {
                return ResourceManager.GetString("logSpotifyConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Spotify jest zamknięte.
        /// </summary>
        internal static string logSpotifyIsClosed {
            get {
                return ResourceManager.GetString("logSpotifyIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify nie połączyło się z API, spróbuj ponownie..
        /// </summary>
        internal static string logSpotifyNotConnected {
            get {
                return ResourceManager.GetString("logSpotifyNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify nie zostało znalezione lub zainstalowane..
        /// </summary>
        internal static string logSpotifyNotFound {
            get {
                return ResourceManager.GetString("logSpotifyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spytify nie może nagrywać jeśli nie korzysta z tego samego urządzenia audio co Spotify. Zobacz F.A.Q..
        /// </summary>
        internal static string logSpotifyPlayingOutsideOfSelectedAudioEndPoint {
            get {
                return ResourceManager.GetString("logSpotifyPlayingOutsideOfSelectedAudioEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Szpeigowanie.
        /// </summary>
        internal static string logStarting {
            get {
                return ResourceManager.GetString("logStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Koniec.
        /// </summary>
        internal static string logStoping {
            get {
                return ResourceManager.GetString("logStoping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Oczekiwanie na zakończenie nagrywania bieżącej ścieżki dźwiękowej.
        /// </summary>
        internal static string logStopRecordingWhenSongEnds {
            get {
                return ResourceManager.GetString("logStopRecordingWhenSongEnds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomijanie: {0} (nagranie już istnieje).
        /// </summary>
        internal static string logTrackExists {
            get {
                return ResourceManager.GetString("logTrackExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Bład: nieznany błąd: {0}.
        /// </summary>
        internal static string logUnknownException {
            get {
                return ResourceManager.GetString("logUnknownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Ostrzeżenie: {0} -channels audio nie jest obsługiwane. Dźwięk zostanie zakodowany do 2 (stereo)..
        /// </summary>
        internal static string logUnsupportedNumberChannels {
            get {
                return ResourceManager.GetString("logUnsupportedNumberChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Ostrzeżenie: częstotliwość próbkowania {0} Hz nie jest obsługiwana. Dźwięk zostanie zakodowany do 48000 Hz..
        /// </summary>
        internal static string logUnsupportedRate {
            get {
                return ResourceManager.GetString("logUnsupportedRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy napewno chcesz wyjść?.
        /// </summary>
        internal static string msgBodyCantQuit {
            get {
                return ResourceManager.GetString("msgBodyCantQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się otworzyć kontrolera Audio Virtual Cable..
        /// </summary>
        internal static string msgBodyDriverInstallationFailed {
            get {
                return ResourceManager.GetString("msgBodyDriverInstallationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utracono połączenie z Spotify API. Upewnij się, że autoryzowałeś Spytify na tym samym koncie Spotify, które jest obecnie połączone z aplikacją Spotify-Desktop, aby móc uzyskać metadane bieżącego utworu. W międzyczasie Spytify będzie używać LastFM API..
        /// </summary>
        internal static string msgBodyFailedToUseSpotifyAPI {
            get {
                return ResourceManager.GetString("msgBodyFailedToUseSpotifyAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten folder nie istnieje, wybierz inny.
        /// </summary>
        internal static string msgBodyPathNotFound {
            get {
                return ResourceManager.GetString("msgBodyPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz inny katalog, wybrana ścieżka wyjściowa jest za długa..
        /// </summary>
        internal static string msgBodyPathTooLong {
            get {
                return ResourceManager.GetString("msgBodyPathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz folder gdzie chcesz zapisać nagrane utwory.
        /// </summary>
        internal static string msgFolderDialog {
            get {
                return ResourceManager.GetString("msgFolderDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy chcesz otworzyć GitHub i zobaczyć najnowszą wersję Spytify?.
        /// </summary>
        internal static string msgNewVersionContent {
            get {
                return ResourceManager.GetString("msgNewVersionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wersja {0} jest dostępna!.
        /// </summary>
        internal static string msgNewVersionTitle {
            get {
                return ResourceManager.GetString("msgNewVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spytify szpieguje.
        /// </summary>
        internal static string msgTitleCantQuit {
            get {
                return ResourceManager.GetString("msgTitleCantQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd API Spotify.
        /// </summary>
        internal static string msgTitleFailedToUseSpotifyAPI {
            get {
                return ResourceManager.GetString("msgTitleFailedToUseSpotifyAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ścieżka docelowa niepoprawna.
        /// </summary>
        internal static string msgTitlePathNotFound {
            get {
                return ResourceManager.GetString("msgTitlePathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zbyt długa ścieżka wyjściowa.
        /// </summary>
        internal static string msgTitlePathTooLong {
            get {
                return ResourceManager.GetString("msgTitlePathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia zaawansowane.
        /// </summary>
        internal static string tabAdvanced {
            get {
                return ResourceManager.GetString("tabAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szpieguj.
        /// </summary>
        internal static string tabRecord {
            get {
                return ResourceManager.GetString("tabRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        internal static string tabSettings {
            get {
                return ResourceManager.GetString("tabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść historię.
        /// </summary>
        internal static string tipClear {
            get {
                return ResourceManager.GetString("tipClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz katalog docelowy.
        /// </summary>
        internal static string tipDirectory {
            get {
                return ResourceManager.GetString("tipDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wesprzyj Spytify.
        /// </summary>
        internal static string tipDonate {
            get {
                return ResourceManager.GetString("tipDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobacz F.A.Q..
        /// </summary>
        internal static string tipFAQ {
            get {
                return ResourceManager.GetString("tipFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobacz, jak skonfigurować i używać Spotify API.
        /// </summary>
        internal static string tipFAQSpotifyAPI {
            get {
                return ResourceManager.GetString("tipFAQSpotifyAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zainstaluj Audio Virtual Cable.
        /// </summary>
        internal static string tipInstallVirtualCableDriver {
            get {
                return ResourceManager.GetString("tipInstallVirtualCableDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTRL wpływa na wartość maski.
        /// </summary>
        internal static string tipNumModifierHold {
            get {
                return ResourceManager.GetString("tipNumModifierHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeglądaj.
        /// </summary>
        internal static string tipPath {
            get {
                return ResourceManager.GetString("tipPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa wersja dostępna.
        /// </summary>
        internal static string tipRelease {
            get {
                return ResourceManager.GetString("tipRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzaj danymi logowania Spotify API.
        /// </summary>
        internal static string tipSpotifyAPICredentials {
            get {
                return ResourceManager.GetString("tipSpotifyAPICredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel interfejsu Spotify API.
        /// </summary>
        internal static string tipSpotifyAPIDashboard {
            get {
                return ResourceManager.GetString("tipSpotifyAPIDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruchom szpiegowanie.
        /// </summary>
        internal static string tipStartSpying {
            get {
                return ResourceManager.GetString("tipStartSpying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatrzymaj szpiegowanie.
        /// </summary>
        internal static string tipStopSying {
            get {
                return ResourceManager.GetString("tipStopSying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odinstaluj Audio Virtual Cable.
        /// </summary>
        internal static string tipUninstallVirtualCableDriver {
            get {
                return ResourceManager.GetString("tipUninstallVirtualCableDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane logowania Spotify API.
        /// </summary>
        internal static string titleSpotifyAPICredentials {
            get {
                return ResourceManager.GetString("titleSpotifyAPICredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wklej Client ID tutaj.
        /// </summary>
        internal static string watermarkClientId {
            get {
                return ResourceManager.GetString("watermarkClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wklej tutaj adres URL przekierowania.
        /// </summary>
        internal static string watermarkRedirectURL {
            get {
                return ResourceManager.GetString("watermarkRedirectURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wklej Client Secret tutaj.
        /// </summary>
        internal static string watermarkSecretId {
            get {
                return ResourceManager.GetString("watermarkSecretId", resourceCulture);
            }
        }
    }
}
