//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EspionSpotify.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pt() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EspionSpotify.Translations.pt", typeof(pt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 128kbps.
        /// </summary>
        internal static string cbOptBitRate128 {
            get {
                return ResourceManager.GetString("cbOptBitRate128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 160kbps.
        /// </summary>
        internal static string cbOptBitRate160 {
            get {
                return ResourceManager.GetString("cbOptBitRate160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 256kbps.
        /// </summary>
        internal static string cbOptBitRate256 {
            get {
                return ResourceManager.GetString("cbOptBitRate256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 320kbps.
        /// </summary>
        internal static string cbOptBitRate320 {
            get {
                return ResourceManager.GetString("cbOptBitRate320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Spotify Free).
        /// </summary>
        internal static string cbOptBitRateSpotifyFree {
            get {
                return ResourceManager.GetString("cbOptBitRateSpotifyFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Alta qualidade (Spotify Premium).
        /// </summary>
        internal static string cbOptBitRateSpotifyPremium {
            get {
                return ResourceManager.GetString("cbOptBitRateSpotifyPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agrupar faixas dentro de suas respectivas pastas.
        /// </summary>
        internal static string lblAddFolders {
            get {
                return ResourceManager.GetString("lblAddFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substituir espaços por underline &quot;_&quot; nos nomes dos arquivos.
        /// </summary>
        internal static string lblAddSeparators {
            get {
                return ResourceManager.GetString("lblAddSeparators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anúncios:.
        /// </summary>
        internal static string lblAds {
            get {
                return ResourceManager.GetString("lblAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivo de Áudio:.
        /// </summary>
        internal static string lblAudioDevice {
            get {
                return ResourceManager.GetString("lblAudioDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualidade de Áudio:.
        /// </summary>
        internal static string lblBitRate {
            get {
                return ResourceManager.GetString("lblBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID:.
        /// </summary>
        internal static string lblClientId {
            get {
                return ResourceManager.GetString("lblClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicar.
        /// </summary>
        internal static string lblDuplicate {
            get {
                return ResourceManager.GetString("lblDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atrasar próxima gravação se a música for detectada.
        /// </summary>
        internal static string lblEndingSongDelay {
            get {
                return ResourceManager.GetString("lblEndingSongDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mova o título extra da faixa para a etiqueta da legenda.
        /// </summary>
        internal static string lblExtraTitleToSubtitle {
            get {
                return ResourceManager.GetString("lblExtraTitleToSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de Áudio:.
        /// </summary>
        internal static string lblFormat {
            get {
                return ResourceManager.GetString("lblFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerais:.
        /// </summary>
        internal static string lblGeneral {
            get {
                return ResourceManager.GetString("lblGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags ID3:.
        /// </summary>
        internal static string lblID3 {
            get {
                return ResourceManager.GetString("lblID3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma:.
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize para a bandeja do sistema.
        /// </summary>
        internal static string lblMinimizeToSystemTray {
            get {
                return ResourceManager.GetString("lblMinimizeToSystemTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duração mínima:.
        /// </summary>
        internal static string lblMinLength {
            get {
                return ResourceManager.GetString("lblMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloquear anúncios.
        /// </summary>
        internal static string lblMuteAds {
            get {
                return ResourceManager.GetString("lblMuteAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicione o número do contador na frente do nome de todos os arquivos.
        /// </summary>
        internal static string lblNumFiles {
            get {
                return ResourceManager.GetString("lblNumFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substitua a etiqueta do número da faixa pelo valor do contador.
        /// </summary>
        internal static string lblNumTracks {
            get {
                return ResourceManager.GetString("lblNumTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Músicas salvas em:.
        /// </summary>
        internal static string lblPath {
            get {
                return ResourceManager.GetString("lblPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluindo anúncios.
        /// </summary>
        internal static string lblRecordAds {
            get {
                return ResourceManager.GetString("lblRecordAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravador:.
        /// </summary>
        internal static string lblRecorder {
            get {
                return ResourceManager.GetString("lblRecorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registre tudo..
        /// </summary>
        internal static string lblRecordEverything {
            get {
                return ResourceManager.GetString("lblRecordEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha a posição inicial do contador.
        /// </summary>
        internal static string lblRecordingNum {
            get {
                return ResourceManager.GetString("lblRecordingNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporizador para a sessão de gravação.
        /// </summary>
        internal static string lblRecordingTimer {
            get {
                return ResourceManager.GetString("lblRecordingTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grave faixas já gravadas em vez de pulá-las..
        /// </summary>
        internal static string lblRecordOverRecordings {
            get {
                return ResourceManager.GetString("lblRecordOverRecordings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL de redirecionamento:.
        /// </summary>
        internal static string lblRedirectURL {
            get {
                return ResourceManager.GetString("lblRedirectURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Secret:.
        /// </summary>
        internal static string lblSecretId {
            get {
                return ResourceManager.GetString("lblSecretId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvir:.
        /// </summary>
        internal static string lblSpy {
            get {
                return ResourceManager.GetString("lblSpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualize novamente as tags ID3 das faixas já gravadas quando forem reproduzidas.
        /// </summary>
        internal static string lblUpdateRecordingsID3Tags {
            get {
                return ResourceManager.GetString("lblUpdateRecordingsID3Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anúncio.
        /// </summary>
        internal static string logAd {
            get {
                return ResourceManager.GetString("logAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removendo: {0} [&lt; {1}s].
        /// </summary>
        internal static string logDeleting {
            get {
                return ResourceManager.GetString("logDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Erro: {0}.
        /// </summary>
        internal static string logException {
            get {
                return ResourceManager.GetString("logException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Contador: Prefixo máximo de sequência de arquivo de {0} atingido.
        /// </summary>
        internal static string logMaxFileSequenceReached {
            get {
                return ResourceManager.GetString("logMaxFileSequenceReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Erro de gravação: arquivos de DLLs não encontradas: libmp3lame.32.dll e libmp3lame.64.dll.
        /// </summary>
        internal static string logMissingDlls {
            get {
                return ResourceManager.GetString("logMissingDlls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Registros de gravações anteriores.
        /// </summary>
        internal static string logPreviousLogs {
            get {
                return ResourceManager.GetString("logPreviousLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravado {0} em: {1}.
        /// </summary>
        internal static string logRecorded {
            get {
                return ResourceManager.GetString("logRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravando: {0}.
        /// </summary>
        internal static string logRecording {
            get {
                return ResourceManager.GetString("logRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Fim do tempo programado para gravação..
        /// </summary>
        internal static string logRecordingTimerDone {
            get {
                return ResourceManager.GetString("logRecordingTimerDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Spotify não está sendo executado, tentando iniciá-lo..
        /// </summary>
        internal static string logSpotifyConnecting {
            get {
                return ResourceManager.GetString("logSpotifyConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Spotify está fechado.
        /// </summary>
        internal static string logSpotifyIsClosed {
            get {
                return ResourceManager.GetString("logSpotifyIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Spotify não se conectou com a API local, por favor tente novamente.
        /// </summary>
        internal static string logSpotifyNotConnected {
            get {
                return ResourceManager.GetString("logSpotifyNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Spotify não foi encontrado ou não está instalado..
        /// </summary>
        internal static string logSpotifyNotFound {
            get {
                return ResourceManager.GetString("logSpotifyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // O Spytify não pode gravar se não usar o mesmo dispositivo de endpoint de áudio do Spotify. Veja o F.A.Q. online para saber como mover o Spotify para outro dispositivo..
        /// </summary>
        internal static string logSpotifyPlayingOutsideOfSelectedAudioEndPoint {
            get {
                return ResourceManager.GetString("logSpotifyPlayingOutsideOfSelectedAudioEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Ouvindo.
        /// </summary>
        internal static string logStarting {
            get {
                return ResourceManager.GetString("logStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Fim.
        /// </summary>
        internal static string logStoping {
            get {
                return ResourceManager.GetString("logStoping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Esperando o término da gravação da faixa atual.
        /// </summary>
        internal static string logStopRecordingWhenSongEnds {
            get {
                return ResourceManager.GetString("logStopRecordingWhenSongEnds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Pulando: {0} (gravação já existe).
        /// </summary>
        internal static string logTrackExists {
            get {
                return ResourceManager.GetString("logTrackExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Erro: Erro desconhecido {0}.
        /// </summary>
        internal static string logUnknownException {
            get {
                return ResourceManager.GetString("logUnknownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Aviso: {0} -canais de áudio não são suportados. O áudio será codificado em 2 (estéreo)..
        /// </summary>
        internal static string logUnsupportedNumberChannels {
            get {
                return ResourceManager.GetString("logUnsupportedNumberChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Aviso: a taxa de amostragem de {0} Hz não é suportada. O áudio será codificado para 48000Hz..
        /// </summary>
        internal static string logUnsupportedRate {
            get {
                return ResourceManager.GetString("logUnsupportedRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ainda deseja sair?.
        /// </summary>
        internal static string msgBodyCantQuit {
            get {
                return ResourceManager.GetString("msgBodyCantQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao iniciar o controlador Audio Virtual Cable..
        /// </summary>
        internal static string msgBodyDriverInstallationFailed {
            get {
                return ResourceManager.GetString("msgBodyDriverInstallationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexão perdida com a API Spotify. Certifique-se de ter autorizado o Spytify na mesma conta do Spotify que está atualmente conectada ao aplicativo Spotify-Desktop para poder obter metadados da faixa atual. Nesse ínterim, o Spytify usará a API LastFM..
        /// </summary>
        internal static string msgBodyFailedToUseSpotifyAPI {
            get {
                return ResourceManager.GetString("msgBodyFailedToUseSpotifyAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caminho de destino inexistente, selecione outro..
        /// </summary>
        internal static string msgBodyPathNotFound {
            get {
                return ResourceManager.GetString("msgBodyPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha outro diretório, o caminho de saída selecionado é muito longo..
        /// </summary>
        internal static string msgBodyPathTooLong {
            get {
                return ResourceManager.GetString("msgBodyPathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione a pasta onde serão salvas as gravações..
        /// </summary>
        internal static string msgFolderDialog {
            get {
                return ResourceManager.GetString("msgFolderDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja abrir o GitHub para baixar a versão mais recente?.
        /// </summary>
        internal static string msgNewVersionContent {
            get {
                return ResourceManager.GetString("msgNewVersionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saiu a versão {0}!.
        /// </summary>
        internal static string msgNewVersionTitle {
            get {
                return ResourceManager.GetString("msgNewVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spytify está ouvindo.
        /// </summary>
        internal static string msgTitleCantQuit {
            get {
                return ResourceManager.GetString("msgTitleCantQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify API Falhou.
        /// </summary>
        internal static string msgTitleFailedToUseSpotifyAPI {
            get {
                return ResourceManager.GetString("msgTitleFailedToUseSpotifyAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caminho de destino inválido.
        /// </summary>
        internal static string msgTitlePathNotFound {
            get {
                return ResourceManager.GetString("msgTitlePathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caminho de saída muito longo.
        /// </summary>
        internal static string msgTitlePathTooLong {
            get {
                return ResourceManager.GetString("msgTitlePathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações avançadas.
        /// </summary>
        internal static string tabAdvanced {
            get {
                return ResourceManager.GetString("tabAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvir.
        /// </summary>
        internal static string tabRecord {
            get {
                return ResourceManager.GetString("tabRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        internal static string tabSettings {
            get {
                return ResourceManager.GetString("tabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar histórico.
        /// </summary>
        internal static string tipClear {
            get {
                return ResourceManager.GetString("tipClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir pasta de destino.
        /// </summary>
        internal static string tipDirectory {
            get {
                return ResourceManager.GetString("tipDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doar para Spytify.
        /// </summary>
        internal static string tipDonate {
            get {
                return ResourceManager.GetString("tipDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver o F.A.Q..
        /// </summary>
        internal static string tipFAQ {
            get {
                return ResourceManager.GetString("tipFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veja como configurar e usar a Spotify API.
        /// </summary>
        internal static string tipFAQSpotifyAPI {
            get {
                return ResourceManager.GetString("tipFAQSpotifyAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalar Audio Virtual Cable.
        /// </summary>
        internal static string tipInstallVirtualCableDriver {
            get {
                return ResourceManager.GetString("tipInstallVirtualCableDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTRL afeta o valor da máscara.
        /// </summary>
        internal static string tipNumModifierHold {
            get {
                return ResourceManager.GetString("tipNumModifierHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navegar.
        /// </summary>
        internal static string tipPath {
            get {
                return ResourceManager.GetString("tipPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova versão disponível.
        /// </summary>
        internal static string tipRelease {
            get {
                return ResourceManager.GetString("tipRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerenciar credenciais Spotify API.
        /// </summary>
        internal static string tipSpotifyAPICredentials {
            get {
                return ResourceManager.GetString("tipSpotifyAPICredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painel Spotify API.
        /// </summary>
        internal static string tipSpotifyAPIDashboard {
            get {
                return ResourceManager.GetString("tipSpotifyAPIDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Começar a ouvir.
        /// </summary>
        internal static string tipStartSpying {
            get {
                return ResourceManager.GetString("tipStartSpying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parar de ouvir.
        /// </summary>
        internal static string tipStopSying {
            get {
                return ResourceManager.GetString("tipStopSying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desinstalar Audio Virtual Cable.
        /// </summary>
        internal static string tipUninstallVirtualCableDriver {
            get {
                return ResourceManager.GetString("tipUninstallVirtualCableDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify API Credentials.
        /// </summary>
        internal static string titleSpotifyAPICredentials {
            get {
                return ResourceManager.GetString("titleSpotifyAPICredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cole o Client ID aqui.
        /// </summary>
        internal static string watermarkClientId {
            get {
                return ResourceManager.GetString("watermarkClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cole o seu URL de redirecionamento aqui.
        /// </summary>
        internal static string watermarkRedirectURL {
            get {
                return ResourceManager.GetString("watermarkRedirectURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cole o Client Secret aqui.
        /// </summary>
        internal static string watermarkSecretId {
            get {
                return ResourceManager.GetString("watermarkSecretId", resourceCulture);
            }
        }
    }
}
