//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EspionSpotify.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class tr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal tr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EspionSpotify.Translations.tr", typeof(tr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 128kbps.
        /// </summary>
        internal static string cbOptBitRate128 {
            get {
                return ResourceManager.GetString("cbOptBitRate128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 160kbps.
        /// </summary>
        internal static string cbOptBitRate160 {
            get {
                return ResourceManager.GetString("cbOptBitRate160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 256kbps.
        /// </summary>
        internal static string cbOptBitRate256 {
            get {
                return ResourceManager.GetString("cbOptBitRate256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 320kbps.
        /// </summary>
        internal static string cbOptBitRate320 {
            get {
                return ResourceManager.GetString("cbOptBitRate320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Spotify Free).
        /// </summary>
        internal static string cbOptBitRateSpotifyFree {
            get {
                return ResourceManager.GetString("cbOptBitRateSpotifyFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Yüksek Kalite (Spotify Premium).
        /// </summary>
        internal static string cbOptBitRateSpotifyPremium {
            get {
                return ResourceManager.GetString("cbOptBitRateSpotifyPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parçaları kendi klasörleri içinde grupla.
        /// </summary>
        internal static string lblAddFolders {
            get {
                return ResourceManager.GetString("lblAddFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya adı alanlarını alt çizgi &quot;_&quot; ile değiştirin.
        /// </summary>
        internal static string lblAddSeparators {
            get {
                return ResourceManager.GetString("lblAddSeparators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reklamlar:.
        /// </summary>
        internal static string lblAds {
            get {
                return ResourceManager.GetString("lblAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ses Cihazı:.
        /// </summary>
        internal static string lblAudioDevice {
            get {
                return ResourceManager.GetString("lblAudioDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ses Kalitesi:.
        /// </summary>
        internal static string lblBitRate {
            get {
                return ResourceManager.GetString("lblBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID:.
        /// </summary>
        internal static string lblClientId {
            get {
                return ResourceManager.GetString("lblClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopyala.
        /// </summary>
        internal static string lblDuplicate {
            get {
                return ResourceManager.GetString("lblDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ses algılanırsa sonraki kaydı geciktir.
        /// </summary>
        internal static string lblEndingSongDelay {
            get {
                return ResourceManager.GetString("lblEndingSongDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parçanın fazladan başlığını altyazı etiketine taşı.
        /// </summary>
        internal static string lblExtraTitleToSubtitle {
            get {
                return ResourceManager.GetString("lblExtraTitleToSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ses formatı:.
        /// </summary>
        internal static string lblFormat {
            get {
                return ResourceManager.GetString("lblFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel:.
        /// </summary>
        internal static string lblGeneral {
            get {
                return ResourceManager.GetString("lblGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3 Etiketleri:.
        /// </summary>
        internal static string lblID3 {
            get {
                return ResourceManager.GetString("lblID3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil:.
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistem tepsisine küçült.
        /// </summary>
        internal static string lblMinimizeToSystemTray {
            get {
                return ResourceManager.GetString("lblMinimizeToSystemTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En düşük uzunluk:.
        /// </summary>
        internal static string lblMinLength {
            get {
                return ResourceManager.GetString("lblMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reklamları sustur.
        /// </summary>
        internal static string lblMuteAds {
            get {
                return ResourceManager.GetString("lblMuteAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayaç numarasını tüm dosya adlarının önüne ekleyin.
        /// </summary>
        internal static string lblNumFiles {
            get {
                return ResourceManager.GetString("lblNumFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parça numarası etiketini sayaç değeriyle değiştirin.
        /// </summary>
        internal static string lblNumTracks {
            get {
                return ResourceManager.GetString("lblNumTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt edilecek konum:.
        /// </summary>
        internal static string lblPath {
            get {
                return ResourceManager.GetString("lblPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reklamlar dahil.
        /// </summary>
        internal static string lblRecordAds {
            get {
                return ResourceManager.GetString("lblRecordAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Cihazı:.
        /// </summary>
        internal static string lblRecorder {
            get {
                return ResourceManager.GetString("lblRecorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Her şeyi kaydedin..
        /// </summary>
        internal static string lblRecordEverything {
            get {
                return ResourceManager.GetString("lblRecordEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayacın başlangıç konumunu seçin.
        /// </summary>
        internal static string lblRecordingNum {
            get {
                return ResourceManager.GetString("lblRecordingNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt oturumu için zamanlayıcı.
        /// </summary>
        internal static string lblRecordingTimer {
            get {
                return ResourceManager.GetString("lblRecordingTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atlamak yerine önceden kaydedilmiş parçaları kaydedin..
        /// </summary>
        internal static string lblRecordOverRecordings {
            get {
                return ResourceManager.GetString("lblRecordOverRecordings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönlendir URL:.
        /// </summary>
        internal static string lblRedirectURL {
            get {
                return ResourceManager.GetString("lblRedirectURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Secret:.
        /// </summary>
        internal static string lblSecretId {
            get {
                return ResourceManager.GetString("lblSecretId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sızdırılanlar:.
        /// </summary>
        internal static string lblSpy {
            get {
                return ResourceManager.GetString("lblSpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önceden kaydedilmiş ID3 etiketlerini oynatıldıklarında yeniden güncelleyin.
        /// </summary>
        internal static string lblUpdateRecordingsID3Tags {
            get {
                return ResourceManager.GetString("lblUpdateRecordingsID3Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reklam.
        /// </summary>
        internal static string logAd {
            get {
                return ResourceManager.GetString("logAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siliniyor: {0} [&lt; {1}s].
        /// </summary>
        internal static string logDeleting {
            get {
                return ResourceManager.GetString("logDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Hata: {0}.
        /// </summary>
        internal static string logException {
            get {
                return ResourceManager.GetString("logException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Sayaç: {0} maksimum dosya dizisi önekine ulaşıldı.
        /// </summary>
        internal static string logMaxFileSequenceReached {
            get {
                return ResourceManager.GetString("logMaxFileSequenceReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Kaydedilirken hata oluştu: DLL dosyaları kayıp - libmp3lame.32.dll ve libmp3lame.64.dll.
        /// </summary>
        internal static string logMissingDlls {
            get {
                return ResourceManager.GetString("logMissingDlls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Önceki kayıt işlemlerinin logları.
        /// </summary>
        internal static string logPreviousLogs {
            get {
                return ResourceManager.GetString("logPreviousLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydedildi: {0}/{1}.
        /// </summary>
        internal static string logRecorded {
            get {
                return ResourceManager.GetString("logRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydedildi: {0}.
        /// </summary>
        internal static string logRecording {
            get {
                return ResourceManager.GetString("logRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Kayıt işlemi zamanlayıcısı sona erdi..
        /// </summary>
        internal static string logRecordingTimerDone {
            get {
                return ResourceManager.GetString("logRecordingTimerDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Spotify açık değil, başlatılmaya çalışılıyor..
        /// </summary>
        internal static string logSpotifyConnecting {
            get {
                return ResourceManager.GetString("logSpotifyConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Spotify kapalı.
        /// </summary>
        internal static string logSpotifyIsClosed {
            get {
                return ResourceManager.GetString("logSpotifyIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Spotify yerel API&apos;a bağlanamadı, lütfen tekrar deneyin..
        /// </summary>
        internal static string logSpotifyNotConnected {
            get {
                return ResourceManager.GetString("logSpotifyNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Spotify bulunamadı. Yüklenmemiş olabilir..
        /// </summary>
        internal static string logSpotifyNotFound {
            get {
                return ResourceManager.GetString("logSpotifyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Spytify, Spotify ile aynı ses cihazını kullanmıyorsa kayıt yapamaz. Spotify&apos;ı başka bir cihaza nasıl taşıyacağınızı öğrenmek için çevrimiçi S.S.S. sayfasını ziyaret edebilirsiniz..
        /// </summary>
        internal static string logSpotifyPlayingOutsideOfSelectedAudioEndPoint {
            get {
                return ResourceManager.GetString("logSpotifyPlayingOutsideOfSelectedAudioEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Sızdırılıyor.
        /// </summary>
        internal static string logStarting {
            get {
                return ResourceManager.GetString("logStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Bitti.
        /// </summary>
        internal static string logStoping {
            get {
                return ResourceManager.GetString("logStoping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Mevcut ses parçasının kaydının bitmesi bekleniyor.
        /// </summary>
        internal static string logStopRecordingWhenSongEnds {
            get {
                return ResourceManager.GetString("logStopRecordingWhenSongEnds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Atlanıyor: {0} (kayıt zaten mevcut).
        /// </summary>
        internal static string logTrackExists {
            get {
                return ResourceManager.GetString("logTrackExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Hata: Bilinmeyen istisna: {0}.
        /// </summary>
        internal static string logUnknownException {
            get {
                return ResourceManager.GetString("logUnknownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Uyarı: {0} -kanalların sesi desteklenmiyor. Ses 2&apos;ye (stereo) kodlanacaktır..
        /// </summary>
        internal static string logUnsupportedNumberChannels {
            get {
                return ResourceManager.GetString("logUnsupportedNumberChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Uyarı: {0} Hz örnek hızı desteklenmiyor. Ses 48000Hz olarak kodlanacaktır..
        /// </summary>
        internal static string logUnsupportedRate {
            get {
                return ResourceManager.GetString("logUnsupportedRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayrılmak istediğinizden emin misiniz?.
        /// </summary>
        internal static string msgBodyCantQuit {
            get {
                return ResourceManager.GetString("msgBodyCantQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Virtual Cable denetleyicisi açılamadı..
        /// </summary>
        internal static string msgBodyDriverInstallationFailed {
            get {
                return ResourceManager.GetString("msgBodyDriverInstallationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify API ile bağlantı kesildi. Mevcut parçanın meta verilerini alabilmek için şu anda Spotify-Desktop uygulamasına bağlı olan aynı Spotify hesabında Spytify&apos;ı yetkilendirdiğinizden emin olun. Bu arada Spytify, LastFM API&apos;yi kullanacaktır..
        /// </summary>
        internal static string msgBodyFailedToUseSpotifyAPI {
            get {
                return ResourceManager.GetString("msgBodyFailedToUseSpotifyAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kayıt yolu mevcut değil, başka bir kayıt yolu seçiniz..
        /// </summary>
        internal static string msgBodyPathNotFound {
            get {
                return ResourceManager.GetString("msgBodyPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başka bir dizin seçin, seçilen çıktı yolu çok uzun..
        /// </summary>
        internal static string msgBodyPathTooLong {
            get {
                return ResourceManager.GetString("msgBodyPathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydedilen ses dosyalarını kaydetmek istediğiniz klasörü seçin..
        /// </summary>
        internal static string msgFolderDialog {
            get {
                return ResourceManager.GetString("msgFolderDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yayınlanan en yeni Spytify sürümünü görmek için GitHub&apos;ı açmak ister misiniz?.
        /// </summary>
        internal static string msgNewVersionContent {
            get {
                return ResourceManager.GetString("msgNewVersionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versiyon {0} çıktı!.
        /// </summary>
        internal static string msgNewVersionTitle {
            get {
                return ResourceManager.GetString("msgNewVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spytify sızdırıyor.
        /// </summary>
        internal static string msgTitleCantQuit {
            get {
                return ResourceManager.GetString("msgTitleCantQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify API Başarısız.
        /// </summary>
        internal static string msgTitleFailedToUseSpotifyAPI {
            get {
                return ResourceManager.GetString("msgTitleFailedToUseSpotifyAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydedilecek yol geçersiz.
        /// </summary>
        internal static string msgTitlePathNotFound {
            get {
                return ResourceManager.GetString("msgTitlePathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış yolu çok uzun.
        /// </summary>
        internal static string msgTitlePathTooLong {
            get {
                return ResourceManager.GetString("msgTitlePathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelişmiş Seçenekler.
        /// </summary>
        internal static string tabAdvanced {
            get {
                return ResourceManager.GetString("tabAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sızdır.
        /// </summary>
        internal static string tabRecord {
            get {
                return ResourceManager.GetString("tabRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        internal static string tabSettings {
            get {
                return ResourceManager.GetString("tabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçmişi temizle.
        /// </summary>
        internal static string tipClear {
            get {
                return ResourceManager.GetString("tipClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt klasörünü aç.
        /// </summary>
        internal static string tipDirectory {
            get {
                return ResourceManager.GetString("tipDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spytify&apos;a bağış yap.
        /// </summary>
        internal static string tipDonate {
            get {
                return ResourceManager.GetString("tipDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.A,Q,.
        /// </summary>
        internal static string tipFAQ {
            get {
                return ResourceManager.GetString("tipFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify API&apos;yi nasıl yapılandıracağınızı ve kullanacağınızı görün.
        /// </summary>
        internal static string tipFAQSpotifyAPI {
            get {
                return ResourceManager.GetString("tipFAQSpotifyAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Virtual Cable&apos;ı yükleyin.
        /// </summary>
        internal static string tipInstallVirtualCableDriver {
            get {
                return ResourceManager.GetString("tipInstallVirtualCableDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTRL, maske değerini etkiler.
        /// </summary>
        internal static string tipNumModifierHold {
            get {
                return ResourceManager.GetString("tipNumModifierHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Araştır.
        /// </summary>
        internal static string tipPath {
            get {
                return ResourceManager.GetString("tipPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni sürüm mevcut.
        /// </summary>
        internal static string tipRelease {
            get {
                return ResourceManager.GetString("tipRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Spotify API credentials.
        /// </summary>
        internal static string tipSpotifyAPICredentials {
            get {
                return ResourceManager.GetString("tipSpotifyAPICredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify API Kontrol Paneli.
        /// </summary>
        internal static string tipSpotifyAPIDashboard {
            get {
                return ResourceManager.GetString("tipSpotifyAPIDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sızdırmaya başla.
        /// </summary>
        internal static string tipStartSpying {
            get {
                return ResourceManager.GetString("tipStartSpying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sızdırmayı durdur.
        /// </summary>
        internal static string tipStopSying {
            get {
                return ResourceManager.GetString("tipStopSying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Virtual Cable&apos;ı Kaldırma.
        /// </summary>
        internal static string tipUninstallVirtualCableDriver {
            get {
                return ResourceManager.GetString("tipUninstallVirtualCableDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify API Kimlik Bilgileri.
        /// </summary>
        internal static string titleSpotifyAPICredentials {
            get {
                return ResourceManager.GetString("titleSpotifyAPICredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID&apos;i buraya yapıştırın.
        /// </summary>
        internal static string watermarkClientId {
            get {
                return ResourceManager.GetString("watermarkClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönlendirme URL&apos;nizi buraya yapıştırın.
        /// </summary>
        internal static string watermarkRedirectURL {
            get {
                return ResourceManager.GetString("watermarkRedirectURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Secret&apos;i buraya yapıştırın.
        /// </summary>
        internal static string watermarkSecretId {
            get {
                return ResourceManager.GetString("watermarkSecretId", resourceCulture);
            }
        }
    }
}
