//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EspionSpotify {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class english {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal english() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EspionSpotify.english", typeof(english).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 128kbps.
        /// </summary>
        internal static string cbOptBitRate128 {
            get {
                return ResourceManager.GetString("cbOptBitRate128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 160kbps.
        /// </summary>
        internal static string cbOptBitRate160 {
            get {
                return ResourceManager.GetString("cbOptBitRate160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 256kbps.
        /// </summary>
        internal static string cbOptBitRate256 {
            get {
                return ResourceManager.GetString("cbOptBitRate256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 320kbps.
        /// </summary>
        internal static string cbOptBitRate320 {
            get {
                return ResourceManager.GetString("cbOptBitRate320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} (Spotify Free).
        /// </summary>
        internal static string cbOptBitRateSpotifyFree {
            get {
                return ResourceManager.GetString("cbOptBitRateSpotifyFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} High quality (Spotify Premium).
        /// </summary>
        internal static string cbOptBitRateSpotifyPremium {
            get {
                return ResourceManager.GetString("cbOptBitRateSpotifyPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        internal static string cbOptLangEn {
            get {
                return ResourceManager.GetString("cbOptLangEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Français.
        /// </summary>
        internal static string cbOptLangFr {
            get {
                return ResourceManager.GetString("cbOptLangFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Group every artist songs inside their own folder.
        /// </summary>
        internal static string lblAddFolders {
            get {
                return ResourceManager.GetString("lblAddFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replace files name spaces by underscores &quot;_&quot;.
        /// </summary>
        internal static string lblAddSeparators {
            get {
                return ResourceManager.GetString("lblAddSeparators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Audio quality (Bitrate):.
        /// </summary>
        internal static string lblBitRate {
            get {
                return ResourceManager.GetString("lblBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Customize:.
        /// </summary>
        internal static string lblCustomize {
            get {
                return ResourceManager.GetString("lblCustomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Audio format:.
        /// </summary>
        internal static string lblFormat {
            get {
                return ResourceManager.GetString("lblFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language:.
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minimal length:.
        /// </summary>
        internal static string lblMinLength {
            get {
                return ResourceManager.GetString("lblMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add the recording order number infront of all files name.
        /// </summary>
        internal static string lblNumFiles {
            get {
                return ResourceManager.GetString("lblNumFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replace track numbers by the recording order number.
        /// </summary>
        internal static string lblNumTracks {
            get {
                return ResourceManager.GetString("lblNumTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Output path:.
        /// </summary>
        internal static string lblPath {
            get {
                return ResourceManager.GetString("lblPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose the starting position of the recording order number.
        /// </summary>
        internal static string lblRecordingNum {
            get {
                return ResourceManager.GetString("lblRecordingNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à //Removing: {0}.
        /// </summary>
        internal static string logDeleting {
            get {
                return ResourceManager.GetString("logDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à //Removing: {0} [&lt; {1}s].
        /// </summary>
        internal static string logDeletingTooShort {
            get {
                return ResourceManager.GetString("logDeletingTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recording: {0}.
        /// </summary>
        internal static string logRecording {
            get {
                return ResourceManager.GetString("logRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à //Spotify is closed.
        /// </summary>
        internal static string logSpotifyIsClosed {
            get {
                return ResourceManager.GetString("logSpotifyIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à //Spotify app has to run.
        /// </summary>
        internal static string logSpotifyNotRunning {
            get {
                return ResourceManager.GetString("logSpotifyNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à //Spying.
        /// </summary>
        internal static string logStarting {
            get {
                return ResourceManager.GetString("logStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à //End.
        /// </summary>
        internal static string logStoping {
            get {
                return ResourceManager.GetString("logStoping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à //Waiting for next title....
        /// </summary>
        internal static string logWaiting {
            get {
                return ResourceManager.GetString("logWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à //Error while recording: Your computer audio format is not supported. Format needs to be &apos;2 channels, 24 bit, 48000 Hz (Studio Quality)&apos; (Control panel &gt; Sound &gt; Properties &gt; Advanced)..
        /// </summary>
        internal static string logWriterIsNull {
            get {
                return ResourceManager.GetString("logWriterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you still want to leave?.
        /// </summary>
        internal static string msgBodyCantQuit {
            get {
                return ResourceManager.GetString("msgBodyCantQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This output path does not exist, select another one..
        /// </summary>
        internal static string msgBodyPathNotFound {
            get {
                return ResourceManager.GetString("msgBodyPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spytify is spying.
        /// </summary>
        internal static string msgTitleCantQuit {
            get {
                return ResourceManager.GetString("msgTitleCantQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Output path invalid.
        /// </summary>
        internal static string msgTitlePathNotFound {
            get {
                return ResourceManager.GetString("msgTitlePathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spy.
        /// </summary>
        internal static string tabRecord {
            get {
                return ResourceManager.GetString("tabRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string tabSettings {
            get {
                return ResourceManager.GetString("tabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear history.
        /// </summary>
        internal static string tipClear {
            get {
                return ResourceManager.GetString("tipClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open output directory.
        /// </summary>
        internal static string tipDirectory {
            get {
                return ResourceManager.GetString("tipDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse.
        /// </summary>
        internal static string tipPath {
            get {
                return ResourceManager.GetString("tipPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start spying.
        /// </summary>
        internal static string tipStartSpying {
            get {
                return ResourceManager.GetString("tipStartSpying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop spying.
        /// </summary>
        internal static string tipStopSying {
            get {
                return ResourceManager.GetString("tipStopSying", resourceCulture);
            }
        }
    }
}
