//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EspionSpotify {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class french {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal french() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EspionSpotify.french", typeof(french).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 128kbps.
        /// </summary>
        internal static string cbOptBitRate128 {
            get {
                return ResourceManager.GetString("cbOptBitRate128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 160kbps.
        /// </summary>
        internal static string cbOptBitRate160 {
            get {
                return ResourceManager.GetString("cbOptBitRate160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 256kbps.
        /// </summary>
        internal static string cbOptBitRate256 {
            get {
                return ResourceManager.GetString("cbOptBitRate256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 320kbps.
        /// </summary>
        internal static string cbOptBitRate320 {
            get {
                return ResourceManager.GetString("cbOptBitRate320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} (Spotify Free).
        /// </summary>
        internal static string cbOptBitRateSpotifyFree {
            get {
                return ResourceManager.GetString("cbOptBitRateSpotifyFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} Haute qualité (Spotify Premium).
        /// </summary>
        internal static string cbOptBitRateSpotifyPremium {
            get {
                return ResourceManager.GetString("cbOptBitRateSpotifyPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        internal static string cbOptLangEn {
            get {
                return ResourceManager.GetString("cbOptLangEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Français.
        /// </summary>
        internal static string cbOptLangFr {
            get {
                return ResourceManager.GetString("cbOptLangFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Regrouper les chansons d&apos;un même artiste dans un dossier au nom de l&apos;artiste.
        /// </summary>
        internal static string lblAddFolders {
            get {
                return ResourceManager.GetString("lblAddFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remplacer les espaces par des underscores &quot;_&quot; dans le nom des fichiers sauvegardés.
        /// </summary>
        internal static string lblAddSeparators {
            get {
                return ResourceManager.GetString("lblAddSeparators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Qualité audio (Bitrate):.
        /// </summary>
        internal static string lblBitRate {
            get {
                return ResourceManager.GetString("lblBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personnaliser:.
        /// </summary>
        internal static string lblCustomize {
            get {
                return ResourceManager.GetString("lblCustomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format audio:.
        /// </summary>
        internal static string lblFormat {
            get {
                return ResourceManager.GetString("lblFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langage:.
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Durée minimale:.
        /// </summary>
        internal static string lblMinLength {
            get {
                return ResourceManager.GetString("lblMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscrire au début du nom des fichiers enregistrés l&apos;ordre d&apos;enregistrement.
        /// </summary>
        internal static string lblNumFiles {
            get {
                return ResourceManager.GetString("lblNumFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remplacer le numéro de position cd (album track) par l&apos;ordre d&apos;enregistrement.
        /// </summary>
        internal static string lblNumTracks {
            get {
                return ResourceManager.GetString("lblNumTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dossier de sauvegarde:.
        /// </summary>
        internal static string lblPath {
            get {
                return ResourceManager.GetString("lblPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier la position de départ du compteur de l&apos;ordre d&apos;enregistrement.
        /// </summary>
        internal static string lblRecordingNum {
            get {
                return ResourceManager.GetString("lblRecordingNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publicité: {0}.
        /// </summary>
        internal static string logCommercialBreak {
            get {
                return ResourceManager.GetString("logCommercialBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à //Effacement de: {0}.
        /// </summary>
        internal static string logDeleting {
            get {
                return ResourceManager.GetString("logDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à //Effacement de: {0} [&lt; {1}s].
        /// </summary>
        internal static string logDeletingTooShort {
            get {
                return ResourceManager.GetString("logDeletingTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrement de: {0}.
        /// </summary>
        internal static string logRecording {
            get {
                return ResourceManager.GetString("logRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à //Spotify est fermé.
        /// </summary>
        internal static string logSpotifyIsClosed {
            get {
                return ResourceManager.GetString("logSpotifyIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à //Veuillez démarrer l\&apos;application Spotify.
        /// </summary>
        internal static string logSpotifyNotRunning {
            get {
                return ResourceManager.GetString("logSpotifyNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à //Début de l&apos;espionnage.
        /// </summary>
        internal static string logStarting {
            get {
                return ResourceManager.GetString("logStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à //Fin de l&apos;espionnage.
        /// </summary>
        internal static string logStoping {
            get {
                return ResourceManager.GetString("logStoping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à //En attente du prochain titre....
        /// </summary>
        internal static string logWaiting {
            get {
                return ResourceManager.GetString("logWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à //Erreur lors de l&apos;enregistrement: Format audio de votre ordinateur non supporté. Le format doit être &apos;2 canaux, 24 bit, 48000 Hz (Studio Quality)&apos; (Panneau de configuration &gt; Son &gt; Propriétés &gt; Avancés)..
        /// </summary>
        internal static string logWriterIsNull {
            get {
                return ResourceManager.GetString("logWriterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous quand même quitter?.
        /// </summary>
        internal static string msgBodyCantQuit {
            get {
                return ResourceManager.GetString("msgBodyCantQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le répertoire de sauvegarde sélectionné n&apos;existe pas, sélectionner un autre..
        /// </summary>
        internal static string msgBodyPathNotFound {
            get {
                return ResourceManager.GetString("msgBodyPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Espionnage Spotify en cours.
        /// </summary>
        internal static string msgTitleCantQuit {
            get {
                return ResourceManager.GetString("msgTitleCantQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Répertoire invalide.
        /// </summary>
        internal static string msgTitlePathNotFound {
            get {
                return ResourceManager.GetString("msgTitlePathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Espion.
        /// </summary>
        internal static string tabRecord {
            get {
                return ResourceManager.GetString("tabRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres.
        /// </summary>
        internal static string tabSettings {
            get {
                return ResourceManager.GetString("tabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Effacer l&apos;historique.
        /// </summary>
        internal static string tipClear {
            get {
                return ResourceManager.GetString("tipClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrir le répertoire de sauvegarde.
        /// </summary>
        internal static string tipDirectory {
            get {
                return ResourceManager.GetString("tipDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parcourir.
        /// </summary>
        internal static string tipPath {
            get {
                return ResourceManager.GetString("tipPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Débuter l&apos;espionnage.
        /// </summary>
        internal static string tipStartSpying {
            get {
                return ResourceManager.GetString("tipStartSpying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrêter l&apos;espionnage.
        /// </summary>
        internal static string tipStopSying {
            get {
                return ResourceManager.GetString("tipStopSying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pub.
        /// </summary>
        internal static string varAd {
            get {
                return ResourceManager.GetString("varAd", resourceCulture);
            }
        }
    }
}
