//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EspionSpotify.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Directory {
            get {
                return ((string)(this["Directory"]));
            }
            set {
                this["Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Bitrate {
            get {
                return ((int)(this["Bitrate"]));
            }
            set {
                this["Bitrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MediaFormat {
            get {
                return ((int)(this["MediaFormat"]));
            }
            set {
                this["MediaFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int MinimumRecordedLengthSeconds {
            get {
                return ((int)(this["MinimumRecordedLengthSeconds"]));
            }
            set {
                this["MinimumRecordedLengthSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GroupByFoldersEnabled {
            get {
                return ((bool)(this["GroupByFoldersEnabled"]));
            }
            set {
                this["GroupByFoldersEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TrackTitleSeparatorEnabled {
            get {
                return ((bool)(this["TrackTitleSeparatorEnabled"]));
            }
            set {
                this["TrackTitleSeparatorEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OrderNumberInfrontOfFileEnabled {
            get {
                return ((bool)(this["OrderNumberInfrontOfFileEnabled"]));
            }
            set {
                this["OrderNumberInfrontOfFileEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OrderNumberInMediaTagEnabled {
            get {
                return ((bool)(this["OrderNumberInMediaTagEnabled"]));
            }
            set {
                this["OrderNumberInMediaTagEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Language {
            get {
                return ((int)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TabNo {
            get {
                return ((int)(this["TabNo"]));
            }
            set {
                this["TabNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableAds {
            get {
                return ((bool)(this["DisableAds"]));
            }
            set {
                this["DisableAds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EndingSongDelayEnabled {
            get {
                return ((bool)(this["EndingSongDelayEnabled"]));
            }
            set {
                this["EndingSongDelayEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MuteAdsEnabled {
            get {
                return ((bool)(this["MuteAdsEnabled"]));
            }
            set {
                this["MuteAdsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RecordUnknownTrackTypeEnabled {
            get {
                return ((bool)(this["RecordUnknownTrackTypeEnabled"]));
            }
            set {
                this["RecordUnknownTrackTypeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AnalyticsCID {
            get {
                return ((string)(this["AnalyticsCID"]));
            }
            set {
                this["AnalyticsCID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("adeventtracker.spotify.com;ads.pubmatic.com;ads-fa.spotify.com;analytics.spotify." +
            "com;audio-sp-dca.spotify.com;audio2.spotify.com;b.scorecardresearch.com;bounceex" +
            "change.com;bs.serving-sys.com;content.bitsontherun.com;core.insightexpressai.com" +
            ";crashdump.spotify.com;d2gi7ultltnc2u.cloudfront.net;d3rt1990lpmkn.cloudfront.ne" +
            "t;desktop.spotify.com;doubleclick.net;ds.serving-sys.com;gads.pubmatic.com;googl" +
            "eads.g.doubleclick.net;googleadservices.com;gtssl2-ocsp.geotrust.com;heads4-ak.s" +
            "potify.com.edgesuite.net;js.moatads.com;log.spotify.com;media-match.com;omaze.co" +
            "m;pagead2.googlesyndication.com;pagead46.l.doubleclick.net;partner.googleadservi" +
            "ces.com;pubads.g.doubleclick.net;redirector.gvt1.com;s0.2mdn.net;securepubads.g." +
            "doubleclick.net;tpc.googlesyndication.com;v.jwpcdn.com;video-ad-stats.googlesynd" +
            "ication.com;weblb-wg.gslb.spotify.com;weblb-wg.gslb.spotify.comcker.spotify.com;" +
            "www.googleadservices.com;www.googletagservices.com;www.omaze.com;adclick.g.doubl" +
            "ecklick.net;adeventtracker.spotify.com;adnxs.com;ads.yahoo.com;ads-fa.spotify.co" +
            "m;agkn.com;analytics.spotify.com;audio2.spotify.com;audio-ec.spotify.com;audio-f" +
            "a.spotify.com;audio-sp.spotify.com;audio-sp-ash.spotify.com;audio-sp-tyo.spotify" +
            ".com;b.scorecardresearch.com;bounceexchange.com;bs.serving-sys.com;cloudfront.ne" +
            "t;content.bitsontherun.com;core.insightexpressai.com;crashdump.spotify.com;d2gi7" +
            "ultltnc2u.cloudfront.net;d3rt1990lpmkn.cloudfront.net;desktop.spotify.com;double" +
            "click.net;ds.serving-sys.com;fastclick.net;googleads.g.doubleclick.net;googleads" +
            "ervices.com;googlesyndication.com;googletagservices.com;gtssl2-ocsp.geotrust.com" +
            ";gvt1.com;heads-fab.spotify.com;js.moatads.com;log.spotify.com;media-match.com;o" +
            "maze.com;open.spotify.com;pagead2.googlesyndication.com;pagead46.l.doubleclick.n" +
            "et;partner.googleadservices.com;pubads.g.doubleclick.net;pubmatic.com;ravenjs.co" +
            "m;redirector.gvt1.com;rlcdn.com;s0.2mdn.net;securepubads.g.doubleclick.net;spcli" +
            "ent.wg.spotify.com;tpc.googlesyndication.com;v.jwpcdn.com;video-ad-stats.googles" +
            "yndication.com;weblb-wg.gslb.spotify.com;www.googleadservices.com;www.googletags" +
            "ervices.com;www.omaze.com")]
        public string AdHosts {
            get {
                return ((string)(this["AdHosts"]));
            }
            set {
                this["AdHosts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DuplicateAlreadyRecordedTrack {
            get {
                return ((bool)(this["DuplicateAlreadyRecordedTrack"]));
            }
            set {
                this["DuplicateAlreadyRecordedTrack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastVersionPrompted {
            get {
                return ((string)(this["LastVersionPrompted"]));
            }
            set {
                this["LastVersionPrompted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioEndPointDeviceIndex {
            get {
                return ((string)(this["AudioEndPointDeviceIndex"]));
            }
            set {
                this["AudioEndPointDeviceIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpotifyAPISecretId {
            get {
                return ((string)(this["SpotifyAPISecretId"]));
            }
            set {
                this["SpotifyAPISecretId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpotifyAPIClientId {
            get {
                return ((string)(this["SpotifyAPIClientId"]));
            }
            set {
                this["SpotifyAPIClientId"] = value;
            }
        }
    }
}
